# Generated by Django 4.2.1 on 2023-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'blogs',
            '0001_initial',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.FloatField(
                default=0,
                verbose_name='Weight'
            ),
        ),
    ]
