# Generated by Django 4.2.1 on 2023-07-17 19:13

from django.db import migrations

import blogs.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            'blogs',
            '0002_alter_post_weight',
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                (
                    'objects',
                    blogs.managers.PostManager()
                ),
            ],
        ),
    ]
